Generate test report

diff --git a/.github/workflows/npm-test.yml b/.github/workflows/npm-test.yml
--- a/.github/workflows/npm-test.yml
+++ b/.github/workflows/npm-test.yml
@@ -15,7 +15,14 @@ jobs:
 
       - name: Run unit tests
         run: npm run test
-        continue-on-error: true
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/junit.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
 
       - name: Run linter
         run: npm run lint
